config/routes.rb
Rails.application.routes.draw do

 root 'recipyes#index'

 devise_for :users, :path => 'u' 

 get 'users/index/:id', to: "users#index", as:"user_recipes"
 get 'users/list', to: "users#list_users", as: "list_users"
 get 'users/list/banned', to: "users#list_banned_users", as: "list_banned_users"
 get 'users/list/recipes', to: "users#list_of_recipes", as: "list_of_recipes"
 get 'users/list/comments', to: "users#list_of_comments", as: "list_of_comments"

 resources :categories, except:[:new,:show]
 resources :relationships, only:[:create]
 get 'delete/:id', to: 'relationships#delete', as:'unfollow' 
 
 resources :users, only: [:show, :destroy] do 
 	member do
 	 patch 'banned'
 	end
 	end
 
 resources :recipyes do
 resources :comments, only: [:create, :destroy]
  
  collection do
   get "search" 
  end

  member do
   put 'like', to: 'recipyes#upvote'
	 end
 end

 get '*path' => redirect('/')
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :upvotes, dependent: :destroy
  has_many :upvoted_recipes, through: :upvotes, source: :recipe

  has_many :follower_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :following, through: :follower_relationships

  has_many :following_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy 
  has_many :followers, through: :following_relationships
  
  has_attached_file :avatar, styles: {medium: "200x200>", thumb: "100x100>" }, default_url: "missing_avatar.png", styles: {thumb: "70x70>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 1.megabytes
 	
 	validates :email, uniqueness: true
 	validates :name, presence:true
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :user_find, only:[:index, :show, :banned, :destroy]
	before_action :user_params, only:[:banned]
  before_action :if_admin, except: [:index, :edit, :show]

 def index
	@recipies = @user.recipes.paginate(page: params[:page], per_page:6).order('created_at DESC')
 end

 def list_users
 	@users = User.where(admin:false).paginate(page: params[:page], per_page:10).order('created_at DESC')
 end
 
 def list_banned_users
 	@users = User.where(banned:true).paginate(page: params[:page], per_page:10).order('created_at DESC')
  render :list_users
 end
 
 def list_of_recipes
  @recipes = Recipe.all.paginate(page: params[:page], per_page:20).order('created_at DESC')
  render :list_users
 end
 
 def list_of_comments
  @comments = Comment.all.paginate(page: params[:page], per_page:10).order('created_at DESC')
  render :list_users
 end

 def banned
  @user.update_attributes(user_params) 
  flash[:success] = "User was unlocked!"  if ! @user.banned?
  flash[:error] = "User was locked!" if @user.banned?
  redirect_to :back
 end

 def destroy
 	@user.destroy 
 	flash[:error] = "#{@user.name.capitalize} was destroyed!"
 	redirect_to list_users_path
 end

 def edit
 end

 def show
  @relationship = Relationship.new
  @users = User.where(admin:false)
  @banned_users_count = User.where(banned:true).count
  @categories = Category.all
  @recipes = Recipe.all
  @comments = Comment.all
 end

 private

 def user_find
  @user = User.find(params[:id]) 
 rescue ActiveRecord::RecordNotFound
  render_404
 end

 def user_params
 	params.require(:user).permit(:banned)
 end

end

app/views/users/index.html.haml
%h2
 %span= link_to ' ', user_path(@user), class:"btn btn-default glyphicon glyphicon-arrow-left", style:"border-radius:50%; top:-3.5px; width:40px;"
 %span="#{@user.name.capitalize} recipes:" 

%hr
= render partial:"recipyes/index"

app/views/users/list_users.html.haml
- if current_page?("/users/list/recipes")
 
 %h2 
  %span= link_to ' ', user_path(current_user), class:"btn btn-default glyphicon glyphicon-arrow-left", style:"border-radius:50%; top:-3.5px; width:40px;"
  %span List of all recipes:
 %br
 
 %table{:border => "1",class:'table table-striped'}
  %tr
   %th Title
   %th Created_by  
   %th Category
   %th Created_at
   %th{:colspan=>"2"} Action
  -@recipes.each do |recipe|
   %tr
    %td=link_to recipe.title.capitalize, recipye_path(recipe)
    %td=link_to recipe.user.name, user_path(recipe.user_id)
    %td
     = recipe.category.name if recipe.category
     = "Unknown" if ! recipe.category
    %td=recipe.created_at.strftime("%B %e, %Y %l:%M %p")
    %td=link_to 'Edit', edit_recipye_path(recipe)
    %td=link_to 'Del', recipye_path(recipe), method: :delete, data:{confirm:"Delete '#{recipe.title.capitalize}'?"}, class:'del'
 %hr/
 = will_paginate @recipes, inner_window:1, outer_window:0

- elsif current_page?("/users/list/comments")
 
 %h2
  %span= link_to ' ', user_path(current_user), class:"btn btn-default glyphicon glyphicon-arrow-left", style:"border-radius:50%; top:-3.5px; width:40px;"
  %span List of all comments:
 %br
 
 %table{:border => "1",class:'table table-striped comments'}
  %tr
   %th Comment
   %th Created by  
   %th Created at
   %th Action
  -@comments.each do |comment|
   %tr
    %td=link_to comment.body.capitalize, recipye_path(comment.recipe_id)
    %td=link_to comment.user.name, user_path(comment.user_id)
    %td=comment.created_at.strftime("%B %e, %Y %l:%M %p")
    %td=link_to 'Del', recipye_comment_path(comment.recipe_id, comment), method: :delete, data:{confirm:"Delete?"}, class:'del'
 %hr/
 = will_paginate @comments, inner_window:1, outer_window:0

- elsif current_page?("/users/list") || current_page?("/users/list/banned")

 %span
  %h2
   %span
   = link_to ' ', user_path(current_user), class:"btn btn-default glyphicon glyphicon-arrow-left", style:"border-radius:50%; top:-3.5px; width:40px;" 
   = "List of all users:" if current_page?("/users/list")
   = "List of banned users:" if current_page?("/users/list/banned")
 
 %br

 - @users.each do |user|
  - if ! user.admin
   %table{:border => "1",class:'table table-striped users'}
    %tr
     %td= link_to image_tag(user.avatar.url(:thumb), class:"avatar"), user_path(user)
     %td= user.name.capitalize
     %td= user.email
     %td
      = form_for user, url:"/users/#{user.id}/banned" do |f|
       - if ! user.banned?
        = f.label 'Lock user'
        = f.check_box :banned, {},true, checked:""
       - else
        = f.label 'Unlock user'
        = f.check_box :banned, {},false, checked:""
       %p= f.submit "Apply", class: "button small btn-default" 
     - if ! current_page?("/users/list/banned")
      %td{min_width:"1px"}= link_to 'Del', user_path(user), method: :delete, class:'del', data:{confirm:"Destroy user?"} 
  %hr
 = will_paginate @users, inner_window:1, outer_window:0

app/views/users/show.html.haml
.registration  
 #left{style:"float:left;margin: 7px 15px 15px 7px;"}
  #{image_tag @user.avatar.url(:thumb), class:"avatar"}
 
 #right
  %p
   -if @user.admin? 
    %b= @user.name.capitalize
    %i{style:"color:grey;"} (Admin)
   -else
    %b= @user.name.capitalize
    %i{style:"color:grey;"} (User)

   - unless current_user == @user
    - if follow?(current_user, @user) 
     %span{style:"float:right;"}= link_to "Unfollow", unfollow_path(@user.id), class:"btn unfollow-button"
    - else 
     = render 'relationships/relationship_form'
  %p
   %span
    %label.glyphicon.glyphicon-envelope
    = @user.email
  %p
   %span 
    %label.glyphicon.glyphicon-time
    = @user.created_at.strftime("%d, %B %Y")
    |
    - if @user.recipes.count == 0
     = render text: "Has #{@user.recipes.count} recipes" 
    - else
     = link_to "Has #{pluralize(@user.recipes.count, 'recipe')}", user_recipes_path

  %span
   <!-- List of followers-->
   %label= button_tag "#{pluralize(@user.followers.count, 'follower')}", type:"button", class:"btn btn-primary followers", "data-toggle"=>"modal", "data-target"=>".bs-example-modal-sm1"

   .modal.fade.bs-example-modal-sm1{tabindex:"-1", role:"dialog"}
    .modal-dialog.modal-sm{role:"document"}
     .modal-content
      %p#follow_title="#{@user.name} followers:"
      %hr
      %ul
      - @user.followers.each do |follower| 
       %p
        %li.avatar
         = link_to (image_tag(follower.avatar.url(:thumb))), user_path(follower)
         %span{style:"padding-left:10px;"}= follower.name
      %hr
   <!-- List of following-->
   %label= button_tag "#{@user.following.count} following", type:"button", class:"btn btn-primary followers", "data-toggle"=>"modal", "data-target"=>".bs-example-modal-sm"

   .modal.fade.bs-example-modal-sm{tabindex:"-1", role:"dialog"}
    .modal-dialog.modal-sm{role:"document"}
     .modal-content
      %p#follow_title="#{@user.name} following:"
      %hr
      %ul
      - @user.following.each do |following| 
       %p
        %li.avatar
         = link_to (image_tag(following.avatar.url(:thumb))), user_path(following)
         %span{style:"margin-left:10px;"}= following.name
      %hr
 #other
  - if user_signed_in?
   - if current_user.admin 
    %hr
    #align_center
     %p
      = link_to "Users (#{@users.count})", list_users_path
      - if @banned_users_count > 0
       = link_to "Banned users (#{@banned_users_count})", list_banned_users_path  
     %p
      = link_to "Categories (#{@categories.count})", categories_path
      = link_to "Recipes (#{@recipes.count})", list_of_recipes_path
     %p
      = link_to "Comments (#{@comments.count})", list_of_comments_path
  %hr
  - if user_signed_in?
   - if current_user.admin || current_user.id == @user.id
    #align_center
     = link_to ' ', :back, class: "glyphicon glyphicon-menu-left"
     = link_to "Edit profile", edit_user_registration_path, class:"btn btn-primary"
   - else
    = link_to ' ', :back, class: "glyphicon glyphicon-menu-left"
     